---
name: Build Tagged Container

on:
  push:
    tags: ["*"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

jobs:
  build-push-container:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Wait for container build cache
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: main
          check-name: Build Container
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate image name for docker
        run: |
          echo "IMAGE_NAME=${REPO,,}" >> ${GITHUB_ENV}

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=sha

      - name: Build/push container image
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha,scope=container
          context: .
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
